// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackTime.Data;

#nullable disable

namespace TrackTime.Migrations
{
    [DbContext(typeof(TrackTimeContext))]
    [Migration("20220722214228_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("TrackTime.Models.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassiveTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("TrackTime.Models.ProcessAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.ToTable("ProcessAliases");
                });

            modelBuilder.Entity("TrackTime.Models.ProcessAlias", b =>
                {
                    b.HasOne("TrackTime.Models.Process", "Process")
                        .WithMany("Aliases")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");
                });

            modelBuilder.Entity("TrackTime.Models.Process", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
